import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles.css";
import Menu from "../components/Menu";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className={"dark:bg-gray-900 w-1/2 mx-auto"}>
            <Menu />
            {children}
        </div>
    );
}
